### ISSUE TITLE
BACK - Atualizar sincronismo e leitura do retorno 16/08/2024

### ISSUE THREAD

**Issue by yxuo** [RJ-SMTR/api-cct#388]
## Tarefas

- [x] Adicionar logs no sincronismo de duração
- [x] Refatorar sincronismo para maior velocidade - **2h**
- [x] Ler Detalhe Z - **1h**
- [x] Atualizar Domingos - **2h**
- [x] Corrigir SFTP: mover e substituir arquivo igual - **20m**

Adicional

- [x] Atualizar sincronismo e retornos em Prod - **5h** (segundo plano)
- [x] Atualizar sincronismo e retornos local- **3h / 5h**
- [x] Atualizar retornos e saúde do servidor em Prod - **2h** (segundo plano)

**Comment by yxuo** [comment]
## Atualizar sincronismo e retornos em Prod

- [ ] Testar leitura do Domingos local apontando para prod- **30 min - 1h**
- [ ] Testar novamente se prod crasha ao ler retorno.
    - Caso sim, alinhar com @williamfl2007 o que fazer sobre isso, pois esta tarefa está atrasada segundo o tempo que definimos.

**Comment by yxuo** [comment]
## Servidor crasha ao ler retorno

Erro:

```log
bigquery:  SELECT CAST(t.data AS STRING) AS `data`, t.hora, CAST(t.datetime_captura AS STRING) AS datetime_captura, CAST(t.datetime_transacao AS STRING) AS datetime_transacao, CAST(t.datetime_processamento AS STRING) AS datetime_processamento, t.datetime_captura AS captureDateTime, t.modo, t.sentido, t.id_veiculo, t.id_cliente, t.id_transacao, t.tipo_pagamento AS tipo_pagamento, t.tipo_transacao_smtr AS tipo_transacao, t.id_tipo_integracao, t.id_integracao, t.latitude, t.longitude, t.stop_id, t.stop_lat, t.stop_lon, t.valor_transacao, t.valor_pagamento, t.versao AS bqDataVersion, t.consorcio, t.operadora, t.id_consorcio, t.id_operadora, o.documento AS operadoraCpfCnpj, c.cnpj AS consorcioCnpj, 'ok' AS status FROM `rj-smtr.br_rj_riodejaneiro_bilhetagem.transacao` t LEFT JOIN `rj-smtr.cadastro.operadoras` o ON o.id_operadora = t.id_operadora LEFT JOIN `rj-smtr.cadastro.consorcios` c ON c.id_consorcio = t.id_consorcio        LEFT JOIN rj-smtr.br_rj_riodejaneiro_bilhetagem.integracao i ON i.id_transacao = t.id_transacao WHERE (DATE(t.datetime_processamento) >= DATE('2024-08-20T00:00:00.000Z') AND DATE(t.datetime_processamento) <= DATE('2024-08-21T23:59:59.999Z')) ORDER BY datetime_processamento DESC
/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:156
            throw new TransactionNotStartedError_1.TransactionNotStartedError();
                  ^

TransactionNotStartedError: Transaction is not started yet, start transaction before committing or rolling it back.
    at PostgresQueryRunner.rollbackTransaction (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:156:19)
    at CnabService.sincronizeTransacaoViewOrdemPgto (/usr/src/app/dist/cnab/cnab.service.js:256:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CronJobsService.syncTransacaoViewOrdemPgto (/usr/src/app/dist/cron-jobs/cron-jobs.service.js:232:9)

Node.js v18.16.0
```
